version: 0.2
phases:
  install:
    commands:
      - echo "Installing HTML validator..."
      - npm install -g htmlhint
  build:
    commands:
      - echo "Running HTML Validation on index.html..."
      - htmlhint index.html
      # CRITICAL FIX: Force Linux to make the scripts executable
      - chmod +x scripts/cleanup.sh
      - chmod +x scripts/reload_nginx.sh
artifacts:
  files:
    - index.html
    - appspec.yml
    # CRITICAL FIX: Explicitly list the files so CodeBuild cannot ignore them
    - scripts/cleanup.sh
    - scripts/reload_nginx.sh
